<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Framework\View\Element\Template */
?>
<div class="aw-afptc__promo-offer-link" data-bind="scope: 'awAfptcPromoOffer'" data-role="aw-afptc-promo-offer-link">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "[data-role=aw-afptc-promo-offer-link]": {
            "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout();?>
        }
    }
</script>
