<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Aheadworks\Afptc\Block\Promo\Renderer\Popup */
?>
<?php
$dataRole = $block->getDataRole();
$scope = $block->getScope();
?>
<div data-role="<?= /* @noEscape */ $dataRole ?>"
     data-bind="scope: '<?= /* @noEscape */ $scope ?>'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "[data-role=<?= /* @noEscape */ $dataRole ?>]": {
            "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout() ?>
        }
    }
</script>
