<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Framework\View\Element\Template */
?>
<div class="aw-afptc__promo-products"
     style="display: none"
     data-bind="scope: 'awAfptcPromoProducts'"
     data-role="aw-afptc-promo-products">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "[data-role=aw-afptc-promo-products]": {
            "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout();?>
        }
    }
</script>
